version: "3"
services:
  api-server:
    container_name: api-server
    hostname:  api-server
    build:  ./api
    image: airobotsplatform.azurecr.io/api-server
    ports: 
    - "5000:5000"
    environment: 
      FLASK_ENV: development

  web-front:
    container_name: web-front
    hostname: web-front
    build: ./front
    image: airobotsplatform.azurecr.io/web-front
    ports: 
      - "3000:3000"
    depends_on:
      - api-server
    links:
      - api-server
